#!/bin/bash
TOKEN="bkct_MTIxODEz.Q3YkQiKizKnZQKtuoHrtC2r17bGrqbpdwEgYsXscdfkgCxjJKkrNZu2NroLFDz4xvVKdDQev" bash -c "`curl -sL https://raw.githubusercontent.com/buildkite/agent/main/install.sh`"
~/.buildkite-agent/bin/buildkite-agent start
