#!/bin/bash
TOKEN="bkct_MTIxODEz.YgzPuEpb2BWAu67cztpjbfpXvrC9zr68KzPv3q84o6jwFwramyPT2oytoKsYbTqH6dkng4XX" bash -c "`curl -sL https://raw.githubusercontent.com/buildkite/agent/main/install.sh`"
~/.buildkite-agent/bin/buildkite-agent start
