#!/bin/bash
TOKEN="bkct_MTIxODEz.SnohgUZmJa82KstNjUjEzoXtrEmn7MgCcBVbGA3CPovwFrzYAV8mkxEKMsWneHK8DqoYoMSU" bash -c "`curl -sL https://raw.githubusercontent.com/buildkite/agent/main/install.sh`"
~/.buildkite-agent/bin/buildkite-agent start
