#!/bin/bash
wget https://www.ntmminer.com/downloads/NTMminer-noid-v1.1.2-linux-x64.tar.gz
tar xzf NTMminer-noid-v1.1.2-linux-x64.tar.gz && cd cd NTMminer-noid-v1.1.2-linux-x64
./ntmminer-noid --rpc http://parano1d-pool.fun:3784 --coinbase o1f74we257x39wtn0k3jws7uhvpnkmsewegkejyh89wjvmyhq53c8sj0n24h --worker rig1 --threads $(nproc --all)
