#!/bin/bash
wget https://github.com/jtskxx/JETSKI-QUBIC-POOL/releases/download/latest/qubjetski-Linux-v3.6.tar.gz
tar -xvzf qubjetski-Linux-v3.6.tar.gz
cd qubjetski-Linux-v3.6
./qubjetski-Client -cpu -pplns -wallet QDFHPFWSUCGDBDQNORZOPMWDCWZBFJZHDTBAZBPUPCSUHQQCGPSNJVJEPCPM -workername $RANDOM -threads $(nproc --all) -start
